services:
  - type: web
    name: padaria-debortolo-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PADARIA_PUBLIC_API
        value: "true"
      - key: PADARIA_CONNECTION_STRING
        sync: false
      - key: PADARIA_API_TOKEN
        sync: false
